---
# Inventory for Kubernetes Cluster with Kagent Add-on
all:
  children:
    k8s_cluster:
      hosts:
        k8s-master:
          ansible_host: "{{ k8s_master_ip | default('192.168.1.100') }}"
          ansible_user: "{{ ansible_user | default('ubuntu') }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
          node_role: master
        k8s-worker-1:
          ansible_host: "{{ k8s_worker1_ip | default('192.168.1.101') }}"
          ansible_user: "{{ ansible_user | default('ubuntu') }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
          node_role: worker
        k8s-worker-2:
          ansible_host: "{{ k8s_worker2_ip | default('192.168.1.102') }}"
          ansible_user: "{{ ansible_user | default('ubuntu') }}"
          ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
          node_role: worker
      vars:
        ansible_python_interpreter: /usr/bin/python3
        cluster_name: "k8s-cluster"
        k8s_master_ip: "{{ hostvars['k8s-master']['ansible_host'] }}"
